"""Compatibility exports for the catalog GeoTIFF builder."""

from eolab_app.catalog.geotiff import (
    ACQUISITION_DATETIME_DESCRIPTION,
    FALLBACK_DATETIME_DESCRIPTION,
    FILE_EXTENSION,
    PROJECTION_EXTENSION,
    RASTER_EXTENSION,
    RFC3339_TIMESTAMP,
    STAC_RASTER_DATA_TYPES,
    SUGGESTED_WARP_BOUNDS_DESCRIPTION,
    build_stac_item,
)
from eolab_app.raster.catalog_contract import (
    COG_MEDIA_TYPE,
    GEOTIFF_MEDIA_TYPE,
    GEOTIFF_MEDIA_TYPES,
    MOUNTED_GEOTIFF_COLLECTION_ID,
    MOUNTED_GEOTIFF_ITEM_ID_PATTERN,
)


__all__ = (
    "ACQUISITION_DATETIME_DESCRIPTION",
    "COG_MEDIA_TYPE",
    "FALLBACK_DATETIME_DESCRIPTION",
    "FILE_EXTENSION",
    "GEOTIFF_MEDIA_TYPE",
    "GEOTIFF_MEDIA_TYPES",
    "MOUNTED_GEOTIFF_COLLECTION_ID",
    "MOUNTED_GEOTIFF_ITEM_ID_PATTERN",
    "PROJECTION_EXTENSION",
    "RASTER_EXTENSION",
    "RFC3339_TIMESTAMP",
    "STAC_RASTER_DATA_TYPES",
    "SUGGESTED_WARP_BOUNDS_DESCRIPTION",
    "build_stac_item",
)
