FROM ghcr.io/stac-utils/pgstac-pypgstac:v0.9.12@sha256:672faad776b55afe15fadb27589c390c4fc93de5bc73e8889d2c29a600c5dba4

COPY catalog/migrate.sh /catalog/migrate.sh
COPY catalog/migrations/ /catalog/migrations/

ENTRYPOINT ["/bin/sh", "/catalog/migrate.sh"]
