FROM python:3.12-alpine

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /opt/eolab-geoserver

COPY geoserver/ ./
COPY src/eolab_infrastructure/ ./eolab_infrastructure/

USER nobody

CMD ["python", "initialize.py"]
