from datetime import UTC, datetime
from typing import Any

from fastapi import HTTPException
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from .models import (
    AssetRecord,
    CollectionRecord,
    ItemRecord,
    LineageRecord,
    WorkflowRunRecord,
)
from .schemas import (
    CollectionCreate,
    DerivedRegisterRequest,
    RegisterItemRequest,
    SearchRequest,
    WorkflowRunCreate,
)
from .stac import (
    bbox_from_geometry,
    bbox_overlaps,
    canonical_item,
    datetime_matches,
    dt_to_str,
    extract_datetime,
    infer_kind,
    metadata_matches,
    serialize_collection,
    serialize_item,
    serialize_item_collection,
    serialize_root,
)


def _coerce_dt(value: datetime | None) -> datetime | None:
    if value is None:
        return None
    if value.tzinfo is None:
        return value.replace(tzinfo=UTC)
    return value.astimezone(UTC)


def _autocreate_collection(
    session: Session, collection_id: str
) -> CollectionRecord:
    record = session.get(CollectionRecord, collection_id)
    if record is not None:
        return record
    record = CollectionRecord(
        id=collection_id,
        title=collection_id,
        description=f"Autogenerated collection {collection_id}",
        license="proprietary",
        keywords_json=[],
        extra_json={},
    )
    session.add(record)
    session.flush()
    return record


def create_collection(
    session: Session, payload: CollectionCreate
) -> CollectionRecord:
    record = session.get(CollectionRecord, payload.id)
    if record is not None:
        return record
    record = CollectionRecord(
        id=payload.id,
        title=payload.title,
        description=payload.description,
        license=payload.license,
        keywords_json=list(payload.keywords),
        extra_json=dict(payload.extra),
    )
    session.add(record)
    session.commit()
    session.refresh(record)
    return record


def list_collections(session: Session) -> list[CollectionRecord]:
    return list(
        session.scalars(
            select(CollectionRecord).order_by(CollectionRecord.id)
        ).all()
    )


def get_collection_record(
    session: Session, collection_id: str
) -> CollectionRecord:
    record = session.get(CollectionRecord, collection_id)
    if record is None:
        raise HTTPException(status_code=404, detail="collection not found")
    return record


def list_collection_items(
    session: Session, collection_id: str
) -> list[ItemRecord]:
    return list(
        session.scalars(
            select(ItemRecord)
            .where(
                ItemRecord.collection_id == collection_id,
                ItemRecord.deleted_at.is_(None),
            )
            .order_by(ItemRecord.created_at.desc())
        ).all()
    )


def get_item_record(
    session: Session, collection_id: str, item_id: str
) -> ItemRecord:
    record = session.scalar(
        select(ItemRecord).where(
            ItemRecord.collection_id == collection_id,
            ItemRecord.item_id == item_id,
            ItemRecord.deleted_at.is_(None),
        )
    )
    if record is None:
        raise HTTPException(status_code=404, detail="item not found")
    return record


def next_version(session: Session, collection_id: str, logical_id: str) -> int:
    current = session.scalar(
        select(func.max(ItemRecord.version)).where(
            ItemRecord.collection_id == collection_id,
            ItemRecord.logical_id == logical_id,
        )
    )
    return int(current or 0) + 1


def _persist_item(
    session: Session,
    collection_id: str,
    kind: str,
    logical_id: str,
    item_doc: dict[str, Any],
) -> ItemRecord:
    item_id = item_doc["id"]
    record = ItemRecord(
        item_id=item_id,
        collection_id=collection_id,
        logical_id=logical_id,
        version=int(item_doc["properties"]["catalog:version"]),
        kind=kind,
        geometry_json=item_doc.get("geometry"),
        bbox_json=item_doc.get("bbox")
        or bbox_from_geometry(item_doc.get("geometry")),
        datetime_value=extract_datetime(item_doc),
        properties_json=item_doc.get("properties") or {},
        assets_json=item_doc.get("assets") or {},
        stac_extensions_json=item_doc.get("stac_extensions") or [],
        links_json=item_doc.get("links") or [],
        raw_json=item_doc,
    )
    session.add(record)
    session.flush()
    for asset_key, asset_doc in (item_doc.get("assets") or {}).items():
        asset = AssetRecord(
            stable_id=asset_doc["catalog:stable_id"],
            item_id=item_id,
            collection_id=collection_id,
            logical_id=logical_id,
            version=record.version,
            asset_key=asset_key,
            href=asset_doc["href"],
            media_type=asset_doc.get("type"),
            roles_json=list(asset_doc.get("roles") or []),
            asset_json=asset_doc,
        )
        session.add(asset)
    session.flush()
    return record


def register_item(session: Session, payload: RegisterItemRequest) -> ItemRecord:
    _autocreate_collection(session, payload.collection_id)
    if payload.item.get("type") not in {None, "Feature"}:
        raise HTTPException(
            status_code=400, detail="only STAC Items are supported"
        )
    logical_id = (
        payload.logical_id
        or (payload.item.get("properties") or {}).get("catalog:logical_id")
        or payload.item.get("id")
    )
    if not logical_id:
        raise HTTPException(
            status_code=400, detail="item id or logical_id is required"
        )
    kind = payload.kind or infer_kind(payload.item)
    version = next_version(session, payload.collection_id, logical_id)
    item_doc = canonical_item(
        payload.collection_id, logical_id, version, payload.item, kind
    )
    record = _persist_item(
        session, payload.collection_id, kind, logical_id, item_doc
    )
    session.commit()
    session.refresh(record)
    return record


def register_bulk(
    session: Session, entries: list[RegisterItemRequest]
) -> list[ItemRecord]:
    records: list[ItemRecord] = []
    for payload in entries:
        _autocreate_collection(session, payload.collection_id)
        if payload.item.get("type") not in {None, "Feature"}:
            raise HTTPException(
                status_code=400, detail="only STAC Items are supported"
            )
        logical_id = (
            payload.logical_id
            or (payload.item.get("properties") or {}).get("catalog:logical_id")
            or payload.item.get("id")
        )
        if not logical_id:
            raise HTTPException(
                status_code=400, detail="item id or logical_id is required"
            )
        kind = payload.kind or infer_kind(payload.item)
        version = next_version(session, payload.collection_id, logical_id)
        item_doc = canonical_item(
            payload.collection_id, logical_id, version, payload.item, kind
        )
        records.append(
            _persist_item(
                session, payload.collection_id, kind, logical_id, item_doc
            )
        )
    session.commit()
    for record in records:
        session.refresh(record)
    return records


def delete_item(
    session: Session, collection_id: str, item_id: str
) -> ItemRecord:
    record = get_item_record(session, collection_id, item_id)
    record.deleted_at = datetime.now(UTC)
    session.add(record)
    session.commit()
    session.refresh(record)
    return record


def register_workflow_run(
    session: Session, payload: WorkflowRunCreate
) -> WorkflowRunRecord:
    record = session.get(WorkflowRunRecord, payload.run_id)
    if record is None:
        record = WorkflowRunRecord(
            run_id=payload.run_id,
            workflow_id=payload.workflow_id,
            metadata_json=dict(payload.metadata),
            started_at=_coerce_dt(payload.started_at),
            ended_at=_coerce_dt(payload.ended_at),
        )
        session.add(record)
    else:
        record.workflow_id = payload.workflow_id
        record.metadata_json = dict(payload.metadata)
        record.started_at = _coerce_dt(payload.started_at)
        record.ended_at = _coerce_dt(payload.ended_at)
        session.add(record)
    session.commit()
    session.refresh(record)
    return record


def get_workflow_run(session: Session, run_id: str) -> WorkflowRunRecord:
    record = session.get(WorkflowRunRecord, run_id)
    if record is None:
        raise HTTPException(status_code=404, detail="workflow run not found")
    return record


def register_derived(
    session: Session, payload: DerivedRegisterRequest
) -> ItemRecord:
    run = session.get(WorkflowRunRecord, payload.workflow_run_id)
    if run is None:
        raise HTTPException(status_code=404, detail="workflow run not found")
    _autocreate_collection(session, payload.collection_id)
    logical_id = (
        payload.logical_id
        or (payload.item.get("properties") or {}).get("catalog:logical_id")
        or payload.item.get("id")
    )
    if not logical_id:
        raise HTTPException(
            status_code=400, detail="item id or logical_id is required"
        )
    for asset_id in payload.source_asset_ids:
        source_asset = session.get(AssetRecord, asset_id)
        if source_asset is None:
            raise HTTPException(
                status_code=404, detail=f"source asset not found: {asset_id}"
            )
        source_item = session.get(ItemRecord, source_asset.item_id)
        if source_item is None or source_item.deleted_at is not None:
            raise HTTPException(
                status_code=404, detail=f"source asset not active: {asset_id}"
            )
    version = next_version(session, payload.collection_id, logical_id)
    item_doc = canonical_item(
        payload.collection_id,
        logical_id,
        version,
        payload.item,
        "derived",
        workflow_run_id=payload.workflow_run_id,
        source_asset_ids=payload.source_asset_ids,
    )
    record = _persist_item(
        session, payload.collection_id, "derived", logical_id, item_doc
    )
    for asset_doc in item_doc["assets"].values():
        for source_asset_id in payload.source_asset_ids:
            session.add(
                LineageRecord(
                    derived_asset_id=asset_doc["catalog:stable_id"],
                    source_asset_id=source_asset_id,
                    run_id=payload.workflow_run_id,
                    relation="derived_from",
                )
            )
    session.commit()
    session.refresh(record)
    return record


def serialize_collection_doc(
    session: Session, collection_id: str, base_url: str
) -> dict[str, Any]:
    record = get_collection_record(session, collection_id)
    items = list_collection_items(session, collection_id)
    return serialize_collection(record, items, base_url)


def serialize_root_doc(session: Session, base_url: str) -> dict[str, Any]:
    return serialize_root(list_collections(session), base_url)


def serialize_collection_items_doc(
    session: Session, collection_id: str, base_url: str
) -> dict[str, Any]:
    records = list_collection_items(session, collection_id)
    items = [serialize_item(record, base_url) for record in records]
    return serialize_item_collection(items, len(items), len(items), base_url)


def _search_candidates(
    session: Session, payload: SearchRequest
) -> list[ItemRecord]:
    records = list(
        session.scalars(
            select(ItemRecord)
            .where(ItemRecord.deleted_at.is_(None))
            .order_by(ItemRecord.created_at.desc())
        ).all()
    )
    if payload.collections:
        allowed = set(payload.collections)
        records = [
            record for record in records if record.collection_id in allowed
        ]
    if payload.ids:
        ids = set(payload.ids)
        records = [record for record in records if record.item_id in ids]
    if payload.kind:
        records = [record for record in records if record.kind == payload.kind]
    if payload.asset_ids:
        item_ids = set(
            session.scalars(
                select(AssetRecord.item_id).where(
                    AssetRecord.stable_id.in_(payload.asset_ids)
                )
            ).all()
        )
        records = [record for record in records if record.item_id in item_ids]
    search_bbox = payload.bbox
    if payload.intersects:
        search_bbox = search_bbox or bbox_from_geometry(payload.intersects)
    if search_bbox:
        records = [
            record
            for record in records
            if bbox_overlaps(record.bbox_json, search_bbox)
        ]
    if payload.datetime:
        records = [
            record
            for record in records
            if datetime_matches(record.datetime_value, payload.datetime)
        ]
    if payload.metadata:
        records = [
            record
            for record in records
            if metadata_matches(record.raw_json, payload.metadata)
        ]
    return records


def search_doc(
    session: Session, payload: SearchRequest, base_url: str
) -> dict[str, Any]:
    records = _search_candidates(session, payload)
    limited = records[: payload.limit]
    items = [serialize_item(record, base_url) for record in limited]
    return serialize_item_collection(
        items, len(records), payload.limit, base_url
    )


def resolve_asset(session: Session, stable_id: str) -> dict[str, Any]:
    asset = session.get(AssetRecord, stable_id)
    if asset is None:
        raise HTTPException(status_code=404, detail="asset not found")
    item = session.get(ItemRecord, asset.item_id)
    if item is None or item.deleted_at is not None:
        raise HTTPException(status_code=404, detail="asset not active")
    return {
        "stable_id": asset.stable_id,
        "href": asset.href,
        "uri": asset.href,
        "collection_id": asset.collection_id,
        "item_id": asset.item_id,
        "logical_id": asset.logical_id,
        "version": asset.version,
        "asset_key": asset.asset_key,
        "type": asset.media_type,
        "roles": list(asset.roles_json or []),
        "asset": dict(asset.asset_json or {}),
    }


def resolve_assets(session: Session, asset_ids: list[str]) -> dict[str, Any]:
    return {
        "assets": [resolve_asset(session, stable_id) for stable_id in asset_ids]
    }


def provenance_doc(session: Session, stable_id: str) -> dict[str, Any]:
    derived = resolve_asset(session, stable_id)
    lineage_rows = list(
        session.scalars(
            select(LineageRecord)
            .where(LineageRecord.derived_asset_id == stable_id)
            .order_by(LineageRecord.id)
        ).all()
    )
    if not lineage_rows:
        return {"derived_asset": derived, "workflow_run": None, "sources": []}
    run = session.get(WorkflowRunRecord, lineage_rows[0].run_id)
    sources = [
        resolve_asset(session, row.source_asset_id) for row in lineage_rows
    ]
    return {
        "derived_asset": derived,
        "workflow_run": (
            None
            if run is None
            else {
                "run_id": run.run_id,
                "workflow_id": run.workflow_id,
                "metadata": dict(run.metadata_json or {}),
                "started_at": dt_to_str(run.started_at),
                "ended_at": dt_to_str(run.ended_at),
            }
        ),
        "sources": sources,
    }
